SOURCE: GTA
TARGET: Cityscapes
NUM_WORKERS: 4
NUM_PATCH_CLUSTERS: 19
NUM_MINI_PATCH_CLUSTERS: 19
TRAIN:
  SET_SOURCE: first500
  DA_METHOD: CrCDA
  MODEL: DeepLabv2
  RESTORE_FROM: ../../pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
  MULTI_LEVEL: False
  LAMBDA_SEG: 1.0
  LAMBDA_C2: 0.0
  LAMBDA_C3: 0.0
  LAMBDA_ENT: 0.0
  LAMBDA_ENT2: 0.0
  LAMBDA_ENT3: 0.0
  LAMBDA_ADV: 0.0
TEST:
  MODE: best