SOURCE: GTA
TARGET: Cityscapes
DATA_DIRECTORY_SOURCE: /beegfs/work/schoebel/dataset/gta5
DATA_DIRECTORY_TARGET: /beegfs/work/shared/cityscapes
EXP_ROOT: /beegfs/work/schoebel/CrCDA
DATA_LIST_SOURCE: /beegfs/work/schoebel/dataset/gta5_list/{}.txt
DATA_LIST_TARGET: /beegfs/work/schoebel/dataset/cityscapes_list/{}.txt
NUM_WORKERS: 4
TRAIN:
  SET_SOURCE: train
  SET_TARGET: train
  INFO_TARGET: /beegfs/work/schoebel/dataset/cityscapes_list/info.json
  RESTORE_FROM: /beegfs/work/schoebel/.pretrained/DeepLab_resnet_pretrained_imagenet.pth
  DA_METHOD: CrCDA
  MODEL: DeepLabv2
  MULTI_LEVEL: False
  LAMBDA_SEG: 1.0
  LAMBDA_C2: 0.005
  LAMBDA_C3: 0.005
  LAMBDA_ENT: 0.00005
  LAMBDA_ENT2: 0.00005
  LAMBDA_ENT3: 0.00005
  LAMBDA_ADV: 0.00005
TEST:
  MODE: best