SOURCE: GTA
TARGET: Cityscapes
DATA_DIRECTORY_SOURCE: /beegfs/work/schoebel/dataset/gta5
DATA_DIRECTORY_TARGET: /beegfs/work/shared/cityscapes
EXP_ROOT: /beegfs/work/schoebel/AdvEnt
DATA_LIST_SOURCE: /beegfs/work/schoebel/dataset/gta5_list/{}.txt
DATA_LIST_TARGET: /beegfs/work/schoebel/dataset/cityscapes_list/{}.txt
EXP_ROOT_SNAPSHOT: /beegfs/work/schoebel/AdvEnt/snapshots
EXP_ROOT_LOGS: /beegfs/work/schoebel/AdvEnt/logs
EXP_ROOT_EVAL: /beegfs/work/schoebel/AdvEnt/eval
NUM_WORKERS: 4
TRAIN:
  SET_SOURCE: train
  SET_TARGET: train
  INFO_TARGET: /beegfs/work/schoebel/dataset/cityscapes_list/info.json
  MODEL: DeepLabv2
  RESTORE_FROM: /beegfs/work/schoebel/.pretrained/DeepLab_resnet_pretrained_imagenet.pth
  DA_METHOD: MinEnt
  MULTI_LEVEL: True
  LAMBDA_ENT_MAIN: 0.001
  LAMBDA_ENT_AUX: 0.0002
TEST:
  MODE: best
  INFO_TARGET: /beegfs/work/schoebel/dataset/cityscapes_list/info.json