SOURCE: GTA
TARGET: Cityscapes
DATA_DIRECTORY_SOURCE: /beegfs/work/shared/gta5
DATA_DIRECTORY_TARGET: /beegfs/work/shared/cityscapes
EXP_ROOT: /beegfs/work/schoebel/AdvEnt
DATA_LIST_SOURCE: /beegfs/work/schoebel/dataset/gta5_list/{}.txt
DATA_LIST_TARGET: /beegfs/work/schoebel/dataset/cityscapes_list/{}.txt
NUM_WORKERS: 4
TRAIN:
  SET_SOURCE: train
  SET_TARGET: train
  INFO_TARGET: /beegfs/work/schoebel/dataset/cityscapes_list/info.json
  DA_METHOD: MinEnt
  MODEL: DeepLabv2
  RESTORE_FROM: /beegfs/work/shared/00_init_weights/pytorch_resnet101-fe_imagenet.pth
  MULTI_LEVEL: True
  LAMBDA_ENT_MAIN: 0.001
  LAMBDA_ENT_AUX: 0.0002
TEST:
  MODE: best